#!/usr/bin/env python3
# Pure-data tables: no ROS/qi imports so woz_node can import them safely.
#
# GESTURES: each entry is either a list of (joints, angles_rad, speed, pause_s) steps
# or a dict {"init": [...], "loop": [...], "cleanup": [...]} for looping gestures.

GESTURES = {
    # --- Head ---
    "look_left": [
        (["HeadYaw"], [0.7], 0.4, 1.5),
        (["HeadYaw"], [0.0], 0.3, 0.0),
    ],
    "look_right": [
        (["HeadYaw"], [-0.7], 0.4, 1.5),
        (["HeadYaw"], [0.0], 0.3, 0.0),
    ],
    "look_up": [
        (["HeadPitch"], [-0.4], 0.4, 1.5),
        (["HeadPitch"], [-0.18], 0.3, 0.0),
    ],
    "look_down": [
        (["HeadPitch"], [0.5], 0.4, 1.5),
        (["HeadPitch"], [-0.18], 0.3, 0.0),
    ],
    # --- Arms ---
    "arms_open": [
        (["LShoulderPitch", "LShoulderRoll", "LElbowRoll", "LElbowYaw", "LHand",
          "RShoulderPitch", "RShoulderRoll", "RElbowRoll", "RElbowYaw", "RHand"],
         [0.5, 1.0, -0.05, -1.57, 1.0,
          0.5, -1.0,  0.05,  1.57, 1.0], 0.4, 2.0),
        (["LShoulderPitch", "LShoulderRoll", "LElbowRoll", "LElbowYaw", "LHand",
          "RShoulderPitch", "RShoulderRoll", "RElbowRoll", "RElbowYaw", "RHand"],
         [1.47, 0.21, -0.42, -1.21, 0.3,
          1.47, -0.21,  0.42,  1.21, 0.3], 0.3, 0.0),
    ],
    "point_forward": [
        (["RShoulderPitch", "RShoulderRoll", "RElbowRoll", "RElbowYaw", "RHand"],
         [0.0, -0.1, 0.05, 1.57, 0.1], 0.4, 2.0),
        (["RShoulderPitch", "RShoulderRoll", "RElbowRoll", "RElbowYaw", "RHand"],
         [1.47, -0.21, 0.42, 1.21, 0.3], 0.3, 0.0),
    ],
    "salute": [
        (["RShoulderPitch", "RShoulderRoll", "RElbowRoll", "RElbowYaw", "RWristYaw", "RHand",
          "HeadPitch"],
         [-0.4, -0.3, 0.9, 0.8, 0.5, 0.0, -0.1], 0.4, 1.5),
        (["RShoulderPitch", "RShoulderRoll", "RElbowRoll", "RElbowYaw", "RWristYaw", "RHand",
          "HeadPitch"],
         [1.47, -0.21, 0.42, 1.21, 0.08, 0.3, -0.18], 0.3, 0.0),
    ],
    "think": [
        (["RShoulderPitch", "RShoulderRoll", "RElbowRoll", "RElbowYaw", "RHand",
          "HeadPitch", "HeadYaw"],
         [0.6, -0.2, 1.2, 0.4, 0.3, 0.2, 0.2], 0.3, 3.0),
        (["RShoulderPitch", "RShoulderRoll", "RElbowRoll", "RElbowYaw", "RHand",
          "HeadPitch", "HeadYaw"],
         [1.47, -0.21, 0.42, 1.21, 0.3, -0.18, 0.0], 0.3, 0.0),
    ],
    "refuse": [
        (["RShoulderPitch", "RShoulderRoll", "RElbowRoll", "HeadYaw"],
         [0.5, -0.8, 0.5, 0.4], 0.5, 0.3),
        (["HeadYaw"], [-0.4], 0.6, 0.3),
        (["HeadYaw"], [0.4], 0.6, 0.3),
        (["HeadYaw"], [-0.4], 0.6, 0.3),
        (["HeadYaw"], [0.0], 0.4, 0.2),
        (["RShoulderPitch", "RShoulderRoll", "RElbowRoll"],
         [1.47, -0.21, 0.42], 0.3, 0.0),
    ],
    "arm_up": [
        (["RShoulderPitch", "RShoulderRoll", "RElbowRoll", "RElbowYaw"],
         [-1.57, -0.1, 0.05, 1.57], 0.3, 1.2),
        (["RShoulderPitch", "RShoulderRoll", "RElbowRoll", "RElbowYaw"],
         [1.47, -0.21, 0.42, 1.21], 0.3, 0.0),
    ],
    "wave": [
        (["RShoulderPitch", "RShoulderRoll", "RElbowRoll", "RElbowYaw"],
         [-0.5, -0.3, 0.05, 1.57], 0.4, 0.6),
        (["RWristYaw"], [-1.0], 0.8, 0.4),
        (["RWristYaw"], [1.0], 0.8, 0.4),
        (["RWristYaw"], [-1.0], 0.8, 0.4),
        (["RWristYaw"], [1.0], 0.8, 0.4),
        (["RShoulderPitch", "RShoulderRoll", "RElbowRoll", "RElbowYaw", "RWristYaw"],
         [1.47, -0.21, 0.42, 1.21, 0.08], 0.3, 0.0),
    ],
    "pat_pat": {
        "init": [
            (["LShoulderPitch", "LShoulderRoll", "LElbowRoll", "LElbowYaw", "LWristYaw", "LHand"],
             [0.1, 0.3, 0.5, -1.57, 1.57, 1.0], 0.4, 0.4),
        ],
        "loop": [
            (["LShoulderPitch"], [0.2], 0.4, 0.5),
            (["LHand"], [0.4], 0.15, 0.6),
            (["LHand"], [1.0], 0.15, 0.4),
            (["LHand"], [0.4], 0.15, 0.6),
            (["LHand"], [1.0], 0.15, 0.4),
            (["LHand"], [0.4], 0.15, 0.6),
            (["LHand"], [1.0], 0.15, 0.3),
            (["LShoulderPitch"], [0.1], 0.4, 0.4),
        ],
        "cleanup": [
            (["LShoulderPitch", "LShoulderRoll", "LElbowRoll", "LElbowYaw", "LWristYaw", "LHand"],
             [1.47, 0.21, -0.42, -1.21, 0.0, 0.3], 0.3, 0.0),
        ],
    },
    "nod": [
        (["HeadPitch"], [0.4], 0.5, 0.4),
        (["HeadPitch"], [-0.1], 0.5, 0.3),
        (["HeadPitch"], [0.4], 0.5, 0.4),
        (["HeadPitch"], [-0.18], 0.3, 0.0),
    ],
    "give_hand": [
        (["LShoulderPitch", "LShoulderRoll", "LElbowRoll", "LElbowYaw", "LHand"],
         [1.2, 0.1, -0.05, -1.57, 1.0], 0.4, 3.0),
        (["LHand"], [0.0], 0.08, 0.0),
    ],
    "give_hand_sitted": [
        (["LShoulderPitch", "LShoulderRoll", "LElbowRoll", "LElbowYaw", "LWristYaw", "LHand"],
         [0.2, 0.1, -0.05, -1.57, -1.57, 1.0], 0.4, 3.0),
        (["LHand"], [0.0], 0.08, 0.0),
    ],
    "give_hand_right": [
        (["RShoulderPitch", "RShoulderRoll", "RElbowRoll", "RElbowYaw", "RHand"],
         [1.2, -0.1, 0.05, 1.57, 1.0], 0.4, 3.0),
        (["RHand"], [0.0], 0.08, 0.0),
    ],
    "give_hand_sitted_right": [
        (["RShoulderPitch", "RShoulderRoll", "RElbowRoll", "RElbowYaw", "RWristYaw", "RHand"],
         [0.2, -0.1, 0.05, 1.57, 1.57, 1.0], 0.4, 3.0),
        (["RHand"], [0.0], 0.08, 0.0),
    ],
    "close_right_hand": [
        (["RHand"], [ 1.0], 0.4, 3.0),
        (["RHand"], [-1.0], 0.08, 0.0),
    ],
    "close_left_hand": [
        (["LHand"], [1.0], 0.4, 3.0),
        (["LHand"], [0.1], 0.08, 0.0),
    ],
    "yay": [
        (["LShoulderPitch", "LShoulderRoll", "LElbowRoll", "LElbowYaw", "LHand",
          "RShoulderPitch", "RShoulderRoll", "RElbowRoll", "RElbowYaw", "RHand"],
         [-1.5, 0.3, -0.05, -1.57, 1.0,
          -1.5, -0.3,  0.05,  1.57, 1.0], 0.6, 0.5),
        (["LShoulderPitch", "RShoulderPitch"], [-1.7, -1.7], 0.8, 0.25),
        (["LShoulderPitch", "RShoulderPitch"], [-1.5, -1.5], 0.8, 0.25),
        (["LShoulderPitch", "RShoulderPitch"], [-1.7, -1.7], 0.8, 0.25),
        (["LShoulderPitch", "RShoulderPitch"], [-1.5, -1.5], 0.8, 0.5),
        (["LShoulderPitch", "LShoulderRoll", "LElbowRoll", "LElbowYaw", "LHand",
          "RShoulderPitch", "RShoulderRoll", "RElbowRoll", "RElbowYaw", "RHand"],
         [1.47, 0.21, -0.42, -1.21, 0.3,
          1.47, -0.21,  0.42,  1.21, 0.3], 0.3, 0.0),
    ],
    "shake_head": [
        (["HeadYaw"], [0.5], 0.5, 0.3),
        (["HeadYaw"], [-0.5], 0.5, 0.3),
        (["HeadYaw"], [0.5], 0.5, 0.3),
        (["HeadYaw"], [-0.5], 0.5, 0.3),
        (["HeadYaw"], [0.0], 0.3, 0.0),
    ],
    "clapping": [
        (["LShoulderPitch","LShoulderRoll","LElbowRoll","LElbowYaw","LHand",
          "RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RHand"],
         [0.9, -0.1, -0.3, -0.5, 0.8,
          0.9,  0.1,  0.3,  0.5, 0.8], 0.4, 0.3),
        (["LElbowRoll","RElbowRoll"], [-0.05, 0.05], 0.9, 0.1),
        (["LElbowRoll","RElbowRoll"], [-0.3,  0.3],  0.9, 0.1),
        (["LElbowRoll","RElbowRoll"], [-0.05, 0.05], 0.9, 0.1),
        (["LElbowRoll","RElbowRoll"], [-0.3,  0.3],  0.9, 0.1),
        (["LElbowRoll","RElbowRoll"], [-0.05, 0.05], 0.9, 0.1),
        (["LShoulderPitch","LShoulderRoll","LElbowRoll","LElbowYaw","LHand",
          "RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RHand"],
         [1.47, 0.21, -0.42, -1.21, 0.3,
          1.47, -0.21,  0.42,  1.21, 0.3], 0.3, 0.0),
    ],
    "sneezing": [
        (["HeadPitch","RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw"],
         [-0.3, 0.5, -0.1, 0.6, 0.8], 0.25, 0.9),
        (["HeadPitch","RShoulderPitch"], [0.45, 1.3], 1.0, 0.4),
        (["HeadPitch","RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw"],
         [-0.18, 1.47, -0.21, 0.42, 1.21], 0.3, 0.0),
    ],
    "head_scratch": [
        (["RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RWristYaw"],
         [-0.2, -0.3, 1.3, 1.0, 0.0], 0.4, 0.4),
        (["RShoulderPitch"], [-0.1], 0.5, 0.25),
        (["RShoulderPitch"], [-0.35], 0.5, 0.25),
        (["RShoulderPitch"], [-0.1], 0.5, 0.25),
        (["RShoulderPitch"], [-0.35], 0.5, 0.25),
        (["RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RWristYaw"],
         [1.47, -0.21, 0.42, 1.21, 0.0], 0.3, 0.0),
    ],
    "peekaboo": [
        (["LShoulderPitch","LShoulderRoll","LElbowRoll","LElbowYaw","LHand",
          "RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RHand"],
         [0.4, 0.0, -0.7, -1.0, 0.2,
          0.4, 0.0,  0.7,  1.0, 0.2], 0.4, 0.8),
        (["LShoulderRoll","LHand","RShoulderRoll","RHand"],
         [0.8, 1.0, -0.8, 1.0], 0.6, 0.7),
        (["LShoulderRoll","LHand","RShoulderRoll","RHand"],
         [0.0, 0.2,  0.0, 0.2], 0.5, 0.7),
        (["LShoulderRoll","LHand","RShoulderRoll","RHand"],
         [0.8, 1.0, -0.8, 1.0], 0.6, 0.5),
        (["LShoulderPitch","LShoulderRoll","LElbowRoll","LElbowYaw","LHand",
          "RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RHand"],
         [1.47, 0.21, -0.42, -1.21, 0.3,
          1.47, -0.21,  0.42,  1.21, 0.3], 0.3, 0.0),
    ],
    "ohno": [
        (["LShoulderPitch","LShoulderRoll","LElbowRoll","LElbowYaw",
          "RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","HeadPitch"],
         [-0.1, 0.5, -0.9, -1.5,
          -0.1, -0.5,  0.9,  1.5, 0.2], 0.5, 1.5),
        (["LShoulderPitch","LShoulderRoll","LElbowRoll","LElbowYaw",
          "RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","HeadPitch"],
         [1.47, 0.21, -0.42, -1.21,
          1.47, -0.21,  0.42,  1.21, -0.18], 0.3, 0.0),
    ],
    "hips": [
        (["LShoulderPitch","LShoulderRoll","LElbowRoll","LElbowYaw","LWristYaw",
          "RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RWristYaw"],
         [1.3, 0.6, -1.3, -0.5, 0.0,
          1.3, -0.6,  1.3,  0.5, 0.0], 0.4, 2.0),
        (["LShoulderPitch","LShoulderRoll","LElbowRoll","LElbowYaw","LWristYaw",
          "RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RWristYaw"],
         [1.47, 0.21, -0.42, -1.21, 0.0,
          1.47, -0.21,  0.42,  1.21, 0.0], 0.3, 0.0),
    ],
    "drink": [
        (["RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RWristYaw","RHand"],
         [0.6, -0.1, 0.9, 1.0, -1.0, 0.5], 0.4, 0.5),
        (["HeadPitch"], [0.3], 0.3, 1.2),
        (["HeadPitch","RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RWristYaw","RHand"],
         [-0.18, 1.47, -0.21, 0.42, 1.21, 0.0, 0.3], 0.3, 0.0),
    ],
    "monkey": [
        (["LShoulderPitch","LShoulderRoll","LElbowRoll","LElbowYaw","LHand",
          "RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RHand"],
         [0.3, 0.8, -0.8, -1.5, 0.6,
          0.3, -0.8,  0.8,  1.5, 0.6], 0.4, 0.3),
        (["LShoulderPitch","RShoulderPitch","HeadYaw"], [0.5, 0.1, -0.3], 0.4, 0.4),
        (["LShoulderPitch","RShoulderPitch","HeadYaw"], [0.1, 0.5,  0.3], 0.4, 0.4),
        (["LShoulderPitch","RShoulderPitch","HeadYaw"], [0.5, 0.1, -0.3], 0.4, 0.4),
        (["LShoulderPitch","RShoulderPitch","HeadYaw"], [0.1, 0.5,  0.3], 0.4, 0.3),
        (["LShoulderPitch","LShoulderRoll","LElbowRoll","LElbowYaw","LHand",
          "RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RHand","HeadYaw"],
         [1.47, 0.21, -0.42, -1.21, 0.3,
          1.47, -0.21,  0.42,  1.21, 0.3, 0.0], 0.3, 0.0),
    ],
    "ecrit": [
        (["RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RWristYaw","RHand"],
         [1.1, -0.1, 0.3, 0.6, 0.0, 0.1], 0.3, 0.3),
        (["RShoulderPitch","RShoulderRoll"], [1.0, -0.2], 0.5, 0.2),
        (["RShoulderPitch","RShoulderRoll"], [1.2,  0.0], 0.5, 0.2),
        (["RShoulderPitch","RShoulderRoll"], [1.0, -0.15], 0.5, 0.2),
        (["RShoulderPitch","RShoulderRoll"], [1.2,  0.05], 0.5, 0.2),
        (["RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RWristYaw","RHand"],
         [1.47, -0.21, 0.42, 1.21, 0.0, 0.3], 0.3, 0.0),
    ],
    "show_tablet": [
        (["LShoulderPitch","LShoulderRoll","LElbowRoll","LElbowYaw","LWristYaw","LHand",
          "RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RWristYaw","RHand"],
         [0.9, -0.1, -0.3, -0.5, 0.9, 0.7,
          0.9,  0.1,  0.3,  0.5, -0.9, 0.7], 0.4, 2.5),
        (["LShoulderPitch","LShoulderRoll","LElbowRoll","LElbowYaw","LWristYaw","LHand",
          "RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RWristYaw","RHand"],
         [1.47, 0.21, -0.42, -1.21, 0.0, 0.3,
          1.47, -0.21,  0.42,  1.21, 0.0, 0.3], 0.3, 0.0),
    ],
    "breathing_exercise": [
        (["LShoulderPitch","LShoulderRoll","RShoulderPitch","RShoulderRoll"],
         [0.3, 0.3, 0.3, -0.3], 0.15, 3.0),
        (["LShoulderPitch","LShoulderRoll","RShoulderPitch","RShoulderRoll"],
         [1.47, 0.21, 1.47, -0.21], 0.15, 2.5),
        (["LShoulderPitch","LShoulderRoll","RShoulderPitch","RShoulderRoll"],
         [0.3, 0.3, 0.3, -0.3], 0.15, 3.0),
        (["LShoulderPitch","LShoulderRoll","RShoulderPitch","RShoulderRoll"],
         [1.47, 0.21, 1.47, -0.21], 0.15, 0.0),
    ],
    "neutral": [
        (["HeadYaw","HeadPitch",
          "LShoulderPitch","LShoulderRoll","LElbowRoll","LElbowYaw","LHand",
          "RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RHand"],
         [0.0, -0.18,
          1.47, 0.21, -0.42, -1.21, 0.3,
          1.47, -0.21,  0.42,  1.21, 0.3], 0.25, 0.0),
    ],
    "sad": [
        (["HeadPitch","LShoulderPitch","LShoulderRoll","RShoulderPitch","RShoulderRoll"],
         [0.45, 1.6, 0.1, 1.6, -0.1], 0.2, 3.0),
        (["HeadPitch","LShoulderPitch","LShoulderRoll","RShoulderPitch","RShoulderRoll"],
         [-0.18, 1.47, 0.21, 1.47, -0.21], 0.3, 0.0),
    ],
    "touch_head_back": [
        (["RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RWristYaw"],
         [-0.5, -0.2, 1.45, 0.3, 0.0], 0.4, 1.5),
        (["RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RWristYaw"],
         [1.47, -0.21, 0.42, 1.21, 0.0], 0.3, 0.0),
    ],
    "hands_on_head": [
        (["LShoulderPitch","LShoulderRoll","LElbowRoll","LElbowYaw",
          "RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw"],
         [-0.1, 0.5, -0.9, -1.5,
          -0.1, -0.5,  0.9,  1.5], 0.4, 2.0),
        (["LShoulderPitch","LShoulderRoll","LElbowRoll","LElbowYaw",
          "RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw"],
         [1.47, 0.21, -0.42, -1.21,
          1.47, -0.21,  0.42,  1.21], 0.3, 0.0),
    ],
    "hands_on_belly": [
        (["LShoulderPitch","LShoulderRoll","LElbowRoll","LElbowYaw","LWristYaw",
          "RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RWristYaw"],
         [1.3, -0.1, -0.9, -1.0, 0.5,
          1.3,  0.1,  0.9,  1.0, -0.5], 0.4, 2.0),
        (["LShoulderPitch","LShoulderRoll","LElbowRoll","LElbowYaw","LWristYaw",
          "RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RWristYaw"],
         [1.47, 0.21, -0.42, -1.21, 0.0,
          1.47, -0.21,  0.42,  1.21, 0.0], 0.3, 0.0),
    ],
    "personal_distance": [
        (["RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RWristYaw","RHand"],
         [0.2, -0.1, 0.05, 1.57, 0.0, 0.9], 0.4, 2.0),
        (["RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RWristYaw","RHand"],
         [1.47, -0.21, 0.42, 1.21, 0.0, 0.3], 0.3, 0.0),
    ],
    "premiere_rencontre": [
        (["HeadPitch"], [0.35], 0.3, 0.5),
        (["HeadPitch"], [-0.18], 0.3, 0.3),
        (["RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RWristYaw","RHand"],
         [-0.4, -0.3, 0.05, 1.57, 0.0, 0.9], 0.4, 0.3),
        (["RWristYaw"], [-1.0], 0.8, 0.2),
        (["RWristYaw"], [ 1.0], 0.8, 0.2),
        (["RWristYaw"], [-1.0], 0.8, 0.2),
        (["RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RWristYaw","RHand"],
         [1.47, -0.21, 0.42, 1.21, 0.0, 0.3], 0.3, 0.0),
    ],
    "fera_mieux": [
        (["RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RWristYaw","RHand"],
         [0.8, -0.2, 0.3, 1.0, -1.5, 0.1], 0.4, 0.5),
        (["HeadPitch"], [0.2], 0.4, 0.3),
        (["HeadPitch"], [-0.1], 0.4, 0.3),
        (["HeadPitch"], [0.2], 0.4, 0.3),
        (["HeadPitch"], [-0.18], 0.4, 0.2),
        (["RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RWristYaw","RHand"],
         [1.47, -0.21, 0.42, 1.21, 0.0, 0.3], 0.3, 0.0),
    ],
    "grandpa": [
        (["HeadYaw","HeadPitch","RShoulderPitch","RElbowRoll"],
         [0.4, 0.1, 1.0, 0.7], 0.15, 1.5),
        (["HeadYaw"], [-0.4], 0.15, 1.5),
        (["HeadYaw","HeadPitch"], [0.0, 0.2], 0.15, 0.8),
        (["HeadPitch","RShoulderPitch","RElbowRoll"],
         [-0.18, 1.47, 0.42], 0.2, 0.0),
    ],
    "luxai_en": [
        (["LShoulderPitch","RShoulderPitch"], [0.0, 1.47], 0.5, 0.3),
        (["LShoulderPitch","RShoulderPitch"], [1.47, 0.0], 0.5, 0.3),
        (["LShoulderPitch","RShoulderPitch"], [0.0, 1.47], 0.5, 0.3),
        (["LShoulderPitch","RShoulderPitch"], [1.47, 0.0], 0.5, 0.3),
        (["LShoulderPitch","RShoulderPitch"], [1.47, 1.47], 0.4, 0.0),
    ],
    "six_seven": {
        "init": [
            (["LShoulderPitch","LShoulderRoll","LElbowRoll","LElbowYaw","LHand","LWristYaw",
              "RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RHand","RWristYaw"],
             [0.6, 0.2, -0.5, -1.0, 1.0, -1.57,
              0.6, -0.2,  0.5,  1.0, 1.0, 1.57], 1.0, 0.0),
        ],
        "loop": [
            (["LShoulderPitch","LShoulderRoll","RShoulderPitch","RShoulderRoll","HeadYaw"],
             [0.55, -0.05, 1.05, 0.05, 0.35], 0.55, 0.35),
            (["LShoulderPitch","LShoulderRoll","RShoulderPitch","RShoulderRoll","HeadYaw"],
             [1.05, -0.05, 0.55, 0.05, -0.35], 0.55, 0.35),
        ],
        "cleanup": [
            (["LShoulderPitch","LShoulderRoll","LElbowRoll","LElbowYaw","LHand",
              "RShoulderPitch","RShoulderRoll","RElbowRoll","RElbowYaw","RHand","HeadYaw"],
             [1.47, 0.21, -0.42, -1.21, 0.3,
              1.47, -0.21,  0.42,  1.21, 0.3, 0.0], 0.3, 0.0),
        ],
    },
}

QT_TO_NAO_MOTION = {
    # --- Greetings ---
    "hi":               "wave",
    "bye":              "wave",
    "bye-bye":          "wave",
    "adieu":            "wave",
    "send_kiss":        "wave",
    "kiss":             "wave",
    # --- Head ---
    "nodding-yes":      "nod",
    "yes":              "nod",
    "thanks":           "nod",
    "no":               "shake_head",
    "head-right-left":  "shake_head",
    "yawn":             "look_up",
    # --- Arms / body ---
    "curious":          "think",
    "bored":            "think",
    "bored_long":       "think",
    "point_front":      "point_forward",
    "come":             "point_forward",
    "show_left":        "point_forward",
    "show_right":       "point_forward",
    "rappel":           "point_forward",
    "begin":            "point_forward",
    "one-arm-up":       "arm_up",
    "up_left":          "arm_up",
    "up_right":         "arm_up",
    "hug":              "arms_open",
    "hands-up":         "arms_open",
    "hands-side":       "arms_open",
    "strong":           "arms_open",
    "challenge":        "arms_open",
    "stretch":          "arms_open",
    "hoora":            "yay",
    "laugh":            "yay",
    "happy":            "yay",
    "surprise":         "yay",
    "refuse":           "refuse",
    "so_what":          "refuse",
    "protect":          "refuse",
    "angry":            "refuse",
    "so":               "refuse",
    "hand-front-hold":  "give_hand",
    "touch-head":       "pat_pat",
    "clapping":           "clapping",
    "handclap":           "clapping",
    "sneezing":           "sneezing",
    "head_scratch":       "head_scratch",
    "peekaboo":           "peekaboo",
    "peekaboo-back":      "peekaboo",
    "ohno":               "ohno",
    "hips":               "hips",
    "hands-on-hip":       "hips",
    "drink":              "drink",
    "monkey":             "monkey",
    "ecrit":              "ecrit",
    "show_tablet":        "show_tablet",
    "breathing_exercise": "breathing_exercise",
    "neutral":            "neutral",
    "sad":                "sad",
    "cry":                "sad",
    "touch-head-back":    "touch_head_back",
    "hands-on-head":      "hands_on_head",
    "hands-on-belly":     "hands_on_belly",
    "personal-distance":  "personal_distance",
    "premiere_rencontre": "premiere_rencontre",
    "premiere_recontre":  "premiere_rencontre",
    "fera_mieux":         "fera_mieux",
    "grandpa":            "grandpa",
    "luxai_en":           "luxai_en",
    "test":               "test",
    "shy":                "think",
    # --- QTrobot emotion subfolder names ---
    "surprised":          "yay",
    "disgusted":          "refuse",
    "calm":               "think",
    "afraid":             "think",
    # --- QTrobot imitation / hands variants → no direct NAO equivalent ---
    "hands_side":         None,
    "hands_side_back":    None,
    "hands_on_head_back": None,
    "hands_on_hip_back":  None,
    "hands_on_belly_back":None,
    "hands_up_back":      None,
    # --- QTrobot-only gestures (no NAO equivalent) ---
    "fly":                None,
    "beep":               None,
    "drive":              None,
    "driving":            None,
    "beeping":            None,
    "phone_call":         None,
    "pretend_play":       None,
    "show_face":          None,
    "show_qt":            None,
    "swipe_right":        None,
    "swipe_left":         None,
    "dance":              None,
    "dance_1_1":          None,
    "dance_1_2":          None,
    "dance_1_3":          None,
    "dance_1_4":          None,
    "dance_2_1":          None,
    "dance_2_2":          None,
    "dance_2_3":          None,
    "dance_2_4":          None,
    "dance_3_1":          None,
    "dance_3_2":          None,
    "dance_3_3":          None,
    "dance_4_1":          None,
    "dance_4_2":          None,
    "dance_4_3":          None,
    "dance_4_4":          None,
    "dance_4_5":          None,
    "dance_4_6":          None,
    # --- Custom university package gestures (QTrobot-only) ---
    "gifle":              None,
    "kill":               None,
    "ymca":               None,
    "dancing_arms":       None,
    "left_righ":          None,
    "bla":                None,
    "soleil":             None,
    "movinghead":         None,
    "headright":          None,
    "headleft":           None,
    "draw":               None,
    "tetehaute":          None,
    "tournepoigne":       None,
    "hackathon":          None,
    "fullciao":           None,
    "ciao":               None,
    "very_sad":           None,
    "very_sad2":          None,
    "tired":              None,
    # --- QTrobot full-path forms missing from QT_TO_NAO_BEHAVIOR ---
    "qt/neutral":         None,
}

BEHAVIORS = {
    # --- Dance / performance ---
    "funny_dancer":       "animations/Stand/Waiting/FunnyDancer_1",
    "air_guitar":         "animations/Stand/Waiting/AirGuitar_1",
    "bandmaster":         "animations/Stand/Waiting/Bandmaster_1",
    "kung_fu":            "animations/Stand/Waiting/KungFu_1",
    "robot_dance":        "animations/Stand/Waiting/Robot_1",
    "zombie":             "animations/Stand/Waiting/Zombie_1",
    "happy_birthday":     "animations/Stand/Waiting/HappyBirthday_1",
    "helicopter":         "animations/Stand/Waiting/Helicopter_1",
    "space_shuttle":      "animations/Stand/Waiting/SpaceShuttle_1",
    "drive_car":          "animations/Stand/Waiting/DriveCar_1",
    "air_juggle":         "animations/Stand/Waiting/AirJuggle_1",
    "funny_slide":        "animations/Stand/Waiting/FunnySlide_1",
    "headbang":           "animations/Stand/Waiting/Headbang_1",
    "knight":             "animations/Stand/Waiting/Knight_1",
    "vacuum":             "animations/Stand/Waiting/Vacuum_1",
    "walk_in_the_shit":   "animations/Stand/Waiting/WalkInTheShit_1",
    # --- Fun / waiting ---
    "show_muscles":       "animations/Stand/Waiting/ShowMuscles_1",
    "show_muscles_2":     "animations/Stand/Waiting/ShowMuscles_2",
    "show_muscles_3":     "animations/Stand/Waiting/ShowMuscles_3",
    "show_muscles_4":     "animations/Stand/Waiting/ShowMuscles_4",
    "show_muscles_5":     "animations/Stand/Waiting/ShowMuscles_5",
    "fitness":            "animations/Stand/Waiting/Fitness_1",
    "fitness_2":          "animations/Stand/Waiting/Fitness_2",
    "fitness_3":          "animations/Stand/Waiting/Fitness_3",
    "stretch_wait":       "animations/Stand/Waiting/Stretch_1",
    "stretch_wait_2":     "animations/Stand/Waiting/Stretch_2",
    "stretch_wait_3":     "animations/Stand/Waiting/Stretch_3",
    "back_rubs":          "animations/Stand/Waiting/BackRubs_1",
    "binoculars":         "animations/Stand/Waiting/Binoculars_1",
    "call_someone":       "animations/Stand/Waiting/CallSomeone_1",
    "drink_wait":         "animations/Stand/Waiting/Drink_1",
    "hide_eyes":          "animations/Stand/Waiting/HideEyes_1",
    "hide_hands":         "animations/Stand/Waiting/HideHands_1",
    "innocent_wait":      "animations/Stand/Waiting/Innocent_1",
    "knock_eye":          "animations/Stand/Waiting/KnockEye_1",
    "look_hand":          "animations/Stand/Waiting/LookHand_1",
    "look_hand_2":        "animations/Stand/Waiting/LookHand_2",
    "love_you":           "animations/Stand/Waiting/LoveYou_1",
    "monster":            "animations/Stand/Waiting/Monster_1",
    "mystical_power":     "animations/Stand/Waiting/MysticalPower_1",
    "play_hands":         "animations/Stand/Waiting/PlayHands_1",
    "play_hands_2":       "animations/Stand/Waiting/PlayHands_2",
    "play_hands_3":       "animations/Stand/Waiting/PlayHands_3",
    "relaxation":         "animations/Stand/Waiting/Relaxation_1",
    "relaxation_2":       "animations/Stand/Waiting/Relaxation_2",
    "relaxation_3":       "animations/Stand/Waiting/Relaxation_3",
    "relaxation_4":       "animations/Stand/Waiting/Relaxation_4",
    "rest":               "animations/Stand/Waiting/Rest_1",
    "scratch_back":       "animations/Stand/Waiting/ScratchBack_1",
    "scratch_bottom":     "animations/Stand/Waiting/ScratchBottom_1",
    "scratch_eye":        "animations/Stand/Waiting/ScratchEye_1",
    "scratch_hand":       "animations/Stand/Waiting/ScratchHand_1",
    "scratch_head":       "animations/Stand/Waiting/ScratchHead_1",
    "scratch_leg":        "animations/Stand/Waiting/ScratchLeg_1",
    "scratch_torso":      "animations/Stand/Waiting/ScratchTorso_1",
    "show_sky_wait":      "animations/Stand/Waiting/ShowSky_1",
    "show_sky_wait_2":    "animations/Stand/Waiting/ShowSky_2",
    "take_picture":       "animations/Stand/Waiting/TakePicture_1",
    "taxi":               "animations/Stand/Waiting/Taxi_1",
    "think":              "animations/Stand/Waiting/Think_1",
    "think_2":            "animations/Stand/Waiting/Think_2",
    "think_3":            "animations/Stand/Waiting/Think_3",
    "think_4":            "animations/Stand/Waiting/Think_4",
    "waddle":             "animations/Stand/Waiting/Waddle_1",
    "waddle_2":           "animations/Stand/Waiting/Waddle_2",
    "wake_up":            "animations/Stand/Waiting/WakeUp_1",
    # --- Positive emotions ---
    "ecstatic":           "animations/Stand/Emotions/Positive/Ecstatic_1",
    "enthusiastic":       "animations/Stand/Emotions/Positive/Enthusiastic_1",
    "excited_anim":       "animations/Stand/Emotions/Positive/Excited_1",
    "excited_anim_2":     "animations/Stand/Emotions/Positive/Excited_2",
    "excited_anim_3":     "animations/Stand/Emotions/Positive/Excited_3",
    "happy_anim":         "animations/Stand/Emotions/Positive/Happy_1",
    "happy_anim_2":       "animations/Stand/Emotions/Positive/Happy_2",
    "happy_anim_3":       "animations/Stand/Emotions/Positive/Happy_3",
    "happy_anim_4":       "animations/Stand/Emotions/Positive/Happy_4",
    "hungry_anim":        "animations/Stand/Emotions/Positive/Hungry_1",
    "hysterical":         "animations/Stand/Emotions/Positive/Hysterical_1",
    "laugh_anim":         "animations/Stand/Emotions/Positive/Laugh_1",
    "laugh_anim_2":       "animations/Stand/Emotions/Positive/Laugh_2",
    "laugh_anim_3":       "animations/Stand/Emotions/Positive/Laugh_3",
    "mocker":             "animations/Stand/Emotions/Positive/Mocker_1",
    "optimistic":         "animations/Stand/Emotions/Positive/Optimistic_1",
    "peaceful":           "animations/Stand/Emotions/Positive/Peaceful_1",
    "proud":              "animations/Stand/Emotions/Positive/Proud_1",
    "proud_2":            "animations/Stand/Emotions/Positive/Proud_2",
    "proud_3":            "animations/Stand/Emotions/Positive/Proud_3",
    "relieved":           "animations/Stand/Emotions/Positive/Relieved_1",
    "shy_anim":           "animations/Stand/Emotions/Positive/Shy_1",
    "shy_anim_2":         "animations/Stand/Emotions/Positive/Shy_2",
    "sure":               "animations/Stand/Emotions/Positive/Sure_1",
    "winner":             "animations/Stand/Emotions/Positive/Winner_1",
    "winner_2":           "animations/Stand/Emotions/Positive/Winner_2",
    "amused":             "animations/Stand/Emotions/Positive/Amused_1",
    "confident":          "animations/Stand/Emotions/Positive/Confident_1",
    # --- Negative emotions ---
    "angry_anim":         "animations/Stand/Emotions/Negative/Angry_1",
    "angry_anim_2":       "animations/Stand/Emotions/Negative/Angry_2",
    "angry_anim_3":       "animations/Stand/Emotions/Negative/Angry_3",
    "angry_anim_4":       "animations/Stand/Emotions/Negative/Angry_4",
    "anxious":            "animations/Stand/Emotions/Negative/Anxious_1",
    "bored_anim":         "animations/Stand/Emotions/Negative/Bored_1",
    "bored_anim_2":       "animations/Stand/Emotions/Negative/Bored_2",
    "disappointed":       "animations/Stand/Emotions/Negative/Disappointed_1",
    "exhausted":          "animations/Stand/Emotions/Negative/Exhausted_1",
    "exhausted_2":        "animations/Stand/Emotions/Negative/Exhausted_2",
    "fear":               "animations/Stand/Emotions/Negative/Fear_1",
    "fear_2":             "animations/Stand/Emotions/Negative/Fear_2",
    "fearful":            "animations/Stand/Emotions/Negative/Fearful_1",
    "frustrated":         "animations/Stand/Emotions/Negative/Frustrated_1",
    "humiliated":         "animations/Stand/Emotions/Negative/Humiliated_1",
    "hurt":               "animations/Stand/Emotions/Negative/Hurt_1",
    "hurt_2":             "animations/Stand/Emotions/Negative/Hurt_2",
    "late":               "animations/Stand/Emotions/Negative/Late_1",
    "sad_anim":           "animations/Stand/Emotions/Negative/Sad_1",
    "sad_anim_2":         "animations/Stand/Emotions/Negative/Sad_2",
    "shocked":            "animations/Stand/Emotions/Negative/Shocked_1",
    "sorry":              "animations/Stand/Emotions/Negative/Sorry_1",
    "surprised_anim":     "animations/Stand/Emotions/Negative/Surprise_1",
    "surprised_anim_2":   "animations/Stand/Emotions/Negative/Surprise_2",
    "surprised_anim_3":   "animations/Stand/Emotions/Negative/Surprise_3",
    # --- Neutral emotions ---
    "alienated":          "animations/Stand/Emotions/Neutral/Alienated_1",
    "annoyed":            "animations/Stand/Emotions/Neutral/Annoyed_1",
    "ask_attention":      "animations/Stand/Emotions/Neutral/AskForAttention_1",
    "ask_attention_2":    "animations/Stand/Emotions/Neutral/AskForAttention_2",
    "ask_attention_3":    "animations/Stand/Emotions/Neutral/AskForAttention_3",
    "cautious":           "animations/Stand/Emotions/Neutral/Cautious_1",
    "confused_anim":      "animations/Stand/Emotions/Neutral/Confused_1",
    "determined":         "animations/Stand/Emotions/Neutral/Determined_1",
    "embarrassed":        "animations/Stand/Emotions/Neutral/Embarrassed_1",
    "hello_anim":         "animations/Stand/Emotions/Neutral/Hello_1",
    "hesitation":         "animations/Stand/Emotions/Neutral/Hesitation_1",
    "innocent_anim":      "animations/Stand/Emotions/Neutral/Innocent_1",
    "lonely":             "animations/Stand/Emotions/Neutral/Lonely_1",
    "mischievous":        "animations/Stand/Emotions/Neutral/Mischievous_1",
    "puzzled":            "animations/Stand/Emotions/Neutral/Puzzled_1",
    "sneeze_anim":        "animations/Stand/Emotions/Neutral/Sneeze",
    "stubborn":           "animations/Stand/Emotions/Neutral/Stubborn_1",
    "suspicious":         "animations/Stand/Emotions/Neutral/Suspicious_1",
    # --- Gestures ---
    "angry_gesture":      "animations/Stand/Gestures/Angry_1",
    "angry_gesture_2":    "animations/Stand/Gestures/Angry_2",
    "angry_gesture_3":    "animations/Stand/Gestures/Angry_3",
    "applause":           "animations/Stand/Gestures/Applause_1",
    "bow":                "animations/Stand/Gestures/BowShort_1",
    "but":                "animations/Stand/Gestures/But_1",
    "calm_down":          "animations/Stand/Gestures/CalmDown_1",
    "calm_down_2":        "animations/Stand/Gestures/CalmDown_2",
    "calm_down_3":        "animations/Stand/Gestures/CalmDown_3",
    "calm_down_4":        "animations/Stand/Gestures/CalmDown_4",
    "calm_down_5":        "animations/Stand/Gestures/CalmDown_5",
    "calm_down_6":        "animations/Stand/Gestures/CalmDown_6",
    "caress":             "animations/Stand/Gestures/Caress_1",
    "caress_2":           "animations/Stand/Gestures/Caress_2",
    "catch_fly":          "animations/Stand/Gestures/CatchFly_1",
    "catch_fly_2":        "animations/Stand/Gestures/CatchFly_2",
    "choice":             "animations/Stand/Gestures/Choice_1",
    "choice_2":           "animations/Stand/Gestures/Choice_2",
    "claw":               "animations/Stand/Gestures/Claw_1",
    "claw_2":             "animations/Stand/Gestures/Claw_2",
    "coaxing":            "animations/Stand/Gestures/Coaxing_1",
    "coaxing_2":          "animations/Stand/Gestures/Coaxing_2",
    "come_on":            "animations/Stand/Gestures/ComeOn_1",
    "confused_gesture":   "animations/Stand/Gestures/Confused_1",
    "confused_gesture_2": "animations/Stand/Gestures/Confused_2",
    "count_one":          "animations/Stand/Gestures/CountOne_1",
    "count_one_2":        "animations/Stand/Gestures/CountOne_2",
    "count_two":          "animations/Stand/Gestures/CountTwo_1",
    "count_two_2":        "animations/Stand/Gestures/CountTwo_2",
    "count_three":        "animations/Stand/Gestures/CountThree_1",
    "count_three_2":      "animations/Stand/Gestures/CountThree_2",
    "count_four":         "animations/Stand/Gestures/CountFour_1",
    "count_four_2":       "animations/Stand/Gestures/CountFour_2",
    "count_five":         "animations/Stand/Gestures/CountFive_1",
    "count_five_2":       "animations/Stand/Gestures/CountFive_2",
    "count_more":         "animations/Stand/Gestures/CountMore_1",
    "count_more_2":       "animations/Stand/Gestures/CountMore_2",
    "desperate":          "animations/Stand/Gestures/Desperate_1",
    "desperate_2":        "animations/Stand/Gestures/Desperate_2",
    "desperate_3":        "animations/Stand/Gestures/Desperate_3",
    "desperate_4":        "animations/Stand/Gestures/Desperate_4",
    "desperate_5":        "animations/Stand/Gestures/Desperate_5",
    "enthusiastic_g":     "animations/Stand/Gestures/Enthusiastic_1",
    "enthusiastic_g2":    "animations/Stand/Gestures/Enthusiastic_2",
    "enthusiastic_g3":    "animations/Stand/Gestures/Enthusiastic_3",
    "enthusiastic_g4":    "animations/Stand/Gestures/Enthusiastic_4",
    "enthusiastic_g5":    "animations/Stand/Gestures/Enthusiastic_5",
    "everything":         "animations/Stand/Gestures/Everything_1",
    "everything_2":       "animations/Stand/Gestures/Everything_2",
    "everything_3":       "animations/Stand/Gestures/Everything_3",
    "everything_4":       "animations/Stand/Gestures/Everything_4",
    "everything_5":       "animations/Stand/Gestures/Everything_5",
    "everything_6":       "animations/Stand/Gestures/Everything_6",
    "excited_gesture":    "animations/Stand/Gestures/Excited_1",
    "explain":            "animations/Stand/Gestures/Explain_1",
    "explain_2":          "animations/Stand/Gestures/Explain_2",
    "explain_3":          "animations/Stand/Gestures/Explain_3",
    "explain_4":          "animations/Stand/Gestures/Explain_4",
    "explain_5":          "animations/Stand/Gestures/Explain_5",
    "explain_6":          "animations/Stand/Gestures/Explain_6",
    "explain_7":          "animations/Stand/Gestures/Explain_7",
    "explain_8":          "animations/Stand/Gestures/Explain_8",
    "explain_9":          "animations/Stand/Gestures/Explain_9",
    "explain_10":         "animations/Stand/Gestures/Explain_10",
    "explain_11":         "animations/Stand/Gestures/Explain_11",
    "far":                "animations/Stand/Gestures/Far_1",
    "far_2":              "animations/Stand/Gestures/Far_2",
    "far_3":              "animations/Stand/Gestures/Far_3",
    "follow":             "animations/Stand/Gestures/Follow_1",
    "freeze":             "animations/Stand/Gestures/Freeze_1",
    "give":               "animations/Stand/Gestures/Give_1",
    "give_2":             "animations/Stand/Gestures/Give_2",
    "give_3":             "animations/Stand/Gestures/Give_3",
    "give_4":             "animations/Stand/Gestures/Give_4",
    "give_5":             "animations/Stand/Gestures/Give_5",
    "give_6":             "animations/Stand/Gestures/Give_6",
    "great":              "animations/Stand/Gestures/Great_1",
    "he_says":            "animations/Stand/Gestures/HeSays_1",
    "he_says_2":          "animations/Stand/Gestures/HeSays_2",
    "he_says_3":          "animations/Stand/Gestures/HeSays_3",
    "hey":                "animations/Stand/Gestures/Hey_1",
    "hey_2":              "animations/Stand/Gestures/Hey_2",
    "hey_3":              "animations/Stand/Gestures/Hey_3",
    "hey_4":              "animations/Stand/Gestures/Hey_4",
    "hey_5":              "animations/Stand/Gestures/Hey_5",
    "hey_6":              "animations/Stand/Gestures/Hey_6",
    "hey_7":              "animations/Stand/Gestures/Hey_7",
    "hide":               "animations/Stand/Gestures/Hide_1",
    "hungry_gesture":     "animations/Stand/Gestures/Hungry_1",
    "i_dont_know":        "animations/Stand/Gestures/IDontKnow_1",
    "i_dont_know_2":      "animations/Stand/Gestures/IDontKnow_2",
    "i_dont_know_3":      "animations/Stand/Gestures/IDontKnow_3",
    "i_dont_know_4":      "animations/Stand/Gestures/IDontKnow_4",
    "i_dont_know_5":      "animations/Stand/Gestures/IDontKnow_5",
    "i_dont_know_6":      "animations/Stand/Gestures/IDontKnow_6",
    "joint_hands":        "animations/Stand/Gestures/JointHands_1",
    "joint_hands_2":      "animations/Stand/Gestures/JointHands_2",
    "joint_hands_3":      "animations/Stand/Gestures/JointHands_3",
    "joy_anim":           "animations/Stand/Gestures/Joy_1",
    "kisses":             "animations/Stand/Gestures/Kisses_1",
    "look":               "animations/Stand/Gestures/Look_1",
    "look_2":             "animations/Stand/Gestures/Look_2",
    "maybe":              "animations/Stand/Gestures/Maybe_1",
    "me":                 "animations/Stand/Gestures/Me_1",
    "me_2":               "animations/Stand/Gestures/Me_2",
    "me_3":               "animations/Stand/Gestures/Me_3",
    "me_4":               "animations/Stand/Gestures/Me_4",
    "me_5":               "animations/Stand/Gestures/Me_5",
    "me_6":               "animations/Stand/Gestures/Me_6",
    "me_7":               "animations/Stand/Gestures/Me_7",
    "me_8":               "animations/Stand/Gestures/Me_8",
    "mime":               "animations/Stand/Gestures/Mime_1",
    "mime_2":             "animations/Stand/Gestures/Mime_2",
    "next":               "animations/Stand/Gestures/Next_1",
    "no_gesture":         "animations/Stand/Gestures/No_1",
    "no_gesture_2":       "animations/Stand/Gestures/No_2",
    "no_gesture_3":       "animations/Stand/Gestures/No_3",
    "no_gesture_4":       "animations/Stand/Gestures/No_4",
    "no_gesture_5":       "animations/Stand/Gestures/No_5",
    "no_gesture_6":       "animations/Stand/Gestures/No_6",
    "no_gesture_7":       "animations/Stand/Gestures/No_7",
    "no_gesture_8":       "animations/Stand/Gestures/No_8",
    "no_gesture_9":       "animations/Stand/Gestures/No_9",
    "nothing":            "animations/Stand/Gestures/Nothing_1",
    "nothing_2":          "animations/Stand/Gestures/Nothing_2",
    "on_the_evening":     "animations/Stand/Gestures/OnTheEvening_1",
    "on_the_evening_2":   "animations/Stand/Gestures/OnTheEvening_2",
    "on_the_evening_3":   "animations/Stand/Gestures/OnTheEvening_3",
    "on_the_evening_4":   "animations/Stand/Gestures/OnTheEvening_4",
    "on_the_evening_5":   "animations/Stand/Gestures/OnTheEvening_5",
    "please":             "animations/Stand/Gestures/Please_1",
    "please_2":           "animations/Stand/Gestures/Please_2",
    "please_3":           "animations/Stand/Gestures/Please_3",
    "reject":             "animations/Stand/Gestures/Reject_1",
    "reject_2":           "animations/Stand/Gestures/Reject_2",
    "reject_3":           "animations/Stand/Gestures/Reject_3",
    "reject_4":           "animations/Stand/Gestures/Reject_4",
    "reject_5":           "animations/Stand/Gestures/Reject_5",
    "reject_6":           "animations/Stand/Gestures/Reject_6",
    "salute_anim":        "animations/Stand/Gestures/Salute_1",
    "salute_anim_2":      "animations/Stand/Gestures/Salute_2",
    "salute_anim_3":      "animations/Stand/Gestures/Salute_3",
    "shoot":              "animations/Stand/Gestures/Shoot_1",
    "show_floor":         "animations/Stand/Gestures/ShowFloor_1",
    "show_floor_2":       "animations/Stand/Gestures/ShowFloor_2",
    "show_floor_3":       "animations/Stand/Gestures/ShowFloor_3",
    "show_floor_4":       "animations/Stand/Gestures/ShowFloor_4",
    "show_floor_5":       "animations/Stand/Gestures/ShowFloor_5",
    "show_sky":           "animations/Stand/Gestures/ShowSky_1",
    "show_sky_2":         "animations/Stand/Gestures/ShowSky_2",
    "show_sky_3":         "animations/Stand/Gestures/ShowSky_3",
    "show_sky_4":         "animations/Stand/Gestures/ShowSky_4",
    "show_sky_5":         "animations/Stand/Gestures/ShowSky_5",
    "show_sky_6":         "animations/Stand/Gestures/ShowSky_6",
    "show_sky_7":         "animations/Stand/Gestures/ShowSky_7",
    "show_sky_8":         "animations/Stand/Gestures/ShowSky_8",
    "show_sky_9":         "animations/Stand/Gestures/ShowSky_9",
    "show_sky_10":        "animations/Stand/Gestures/ShowSky_10",
    "show_sky_11":        "animations/Stand/Gestures/ShowSky_11",
    "show_sky_12":        "animations/Stand/Gestures/ShowSky_12",
    "shy_gesture":        "animations/Stand/Gestures/Shy_1",
    "stretch_gesture":    "animations/Stand/Gestures/Stretch_1",
    "stretch_gesture_2":  "animations/Stand/Gestures/Stretch_2",
    "surprised_gesture":  "animations/Stand/Gestures/Surprised_1",
    "take":               "animations/Stand/Gestures/Take_1",
    "thinking_anim":      "animations/Stand/Gestures/Thinking_1",
    "thinking_anim_2":    "animations/Stand/Gestures/Thinking_2",
    "thinking_anim_3":    "animations/Stand/Gestures/Thinking_3",
    "thinking_anim_4":    "animations/Stand/Gestures/Thinking_4",
    "thinking_anim_5":    "animations/Stand/Gestures/Thinking_5",
    "thinking_anim_6":    "animations/Stand/Gestures/Thinking_6",
    "thinking_anim_7":    "animations/Stand/Gestures/Thinking_7",
    "thinking_anim_8":    "animations/Stand/Gestures/Thinking_8",
    "this":               "animations/Stand/Gestures/This_1",
    "this_2":             "animations/Stand/Gestures/This_2",
    "this_3":             "animations/Stand/Gestures/This_3",
    "this_4":             "animations/Stand/Gestures/This_4",
    "this_5":             "animations/Stand/Gestures/This_5",
    "this_6":             "animations/Stand/Gestures/This_6",
    "this_7":             "animations/Stand/Gestures/This_7",
    "this_8":             "animations/Stand/Gestures/This_8",
    "this_9":             "animations/Stand/Gestures/This_9",
    "this_10":            "animations/Stand/Gestures/This_10",
    "this_11":            "animations/Stand/Gestures/This_11",
    "this_12":            "animations/Stand/Gestures/This_12",
    "this_13":            "animations/Stand/Gestures/This_13",
    "this_14":            "animations/Stand/Gestures/This_14",
    "this_15":            "animations/Stand/Gestures/This_15",
    "whats_this":         "animations/Stand/Gestures/WhatSThis_1",
    "whats_this_2":       "animations/Stand/Gestures/WhatSThis_2",
    "whats_this_3":       "animations/Stand/Gestures/WhatSThis_3",
    "whats_this_4":       "animations/Stand/Gestures/WhatSThis_4",
    "whats_this_5":       "animations/Stand/Gestures/WhatSThis_5",
    "whats_this_6":       "animations/Stand/Gestures/WhatSThis_6",
    "whats_this_7":       "animations/Stand/Gestures/WhatSThis_7",
    "whats_this_8":       "animations/Stand/Gestures/WhatSThis_8",
    "whats_this_9":       "animations/Stand/Gestures/WhatSThis_9",
    "whats_this_10":      "animations/Stand/Gestures/WhatSThis_10",
    "whats_this_11":      "animations/Stand/Gestures/WhatSThis_11",
    "whats_this_12":      "animations/Stand/Gestures/WhatSThis_12",
    "whats_this_13":      "animations/Stand/Gestures/WhatSThis_13",
    "whats_this_14":      "animations/Stand/Gestures/WhatSThis_14",
    "whats_this_15":      "animations/Stand/Gestures/WhatSThis_15",
    "whats_this_16":      "animations/Stand/Gestures/WhatSThis_16",
    "wings":              "animations/Stand/Gestures/Wings_1",
    "wings_2":            "animations/Stand/Gestures/Wings_2",
    "wings_3":            "animations/Stand/Gestures/Wings_3",
    "wings_4":            "animations/Stand/Gestures/Wings_4",
    "wings_5":            "animations/Stand/Gestures/Wings_5",
    "yes_anim":           "animations/Stand/Gestures/Yes_1",
    "yes_anim_2":         "animations/Stand/Gestures/Yes_2",
    "yes_anim_3":         "animations/Stand/Gestures/Yes_3",
    "you":                "animations/Stand/Gestures/You_1",
    "you_2":              "animations/Stand/Gestures/You_2",
    "you_3":              "animations/Stand/Gestures/You_3",
    "you_4":              "animations/Stand/Gestures/You_4",
    "you_5":              "animations/Stand/Gestures/You_5",
    "you_know_what":      "animations/Stand/Gestures/YouKnowWhat_1",
    "you_know_what_2":    "animations/Stand/Gestures/YouKnowWhat_2",
    "you_know_what_3":    "animations/Stand/Gestures/YouKnowWhat_3",
    "you_know_what_4":    "animations/Stand/Gestures/YouKnowWhat_4",
    "you_know_what_5":    "animations/Stand/Gestures/YouKnowWhat_5",
    "you_know_what_6":    "animations/Stand/Gestures/YouKnowWhat_6",
    "yum":                "animations/Stand/Gestures/Yum_1",
    # --- Body language (speaking / listening / thinking) ---
    "bodytalk_1":         "animations/Stand/BodyTalk/Speaking/BodyTalk_1",
    "bodytalk_2":         "animations/Stand/BodyTalk/Speaking/BodyTalk_2",
    "bodytalk_3":         "animations/Stand/BodyTalk/Speaking/BodyTalk_3",
    "bodytalk_4":         "animations/Stand/BodyTalk/Speaking/BodyTalk_4",
    "bodytalk_5":         "animations/Stand/BodyTalk/Speaking/BodyTalk_5",
    "bodytalk_6":         "animations/Stand/BodyTalk/Speaking/BodyTalk_6",
    "bodytalk_7":         "animations/Stand/BodyTalk/Speaking/BodyTalk_7",
    "bodytalk_8":         "animations/Stand/BodyTalk/Speaking/BodyTalk_8",
    "bodytalk_9":         "animations/Stand/BodyTalk/Speaking/BodyTalk_9",
    "bodytalk_10":        "animations/Stand/BodyTalk/Speaking/BodyTalk_10",
    "bodytalk_11":        "animations/Stand/BodyTalk/Speaking/BodyTalk_11",
    "bodytalk_12":        "animations/Stand/BodyTalk/Speaking/BodyTalk_12",
    "bodytalk_13":        "animations/Stand/BodyTalk/Speaking/BodyTalk_13",
    "bodytalk_14":        "animations/Stand/BodyTalk/Speaking/BodyTalk_14",
    "bodytalk_15":        "animations/Stand/BodyTalk/Speaking/BodyTalk_15",
    "bodytalk_16":        "animations/Stand/BodyTalk/Speaking/BodyTalk_16",
    "bodytalk_17":        "animations/Stand/BodyTalk/Speaking/BodyTalk_17",
    "bodytalk_18":        "animations/Stand/BodyTalk/Speaking/BodyTalk_18",
    "bodytalk_19":        "animations/Stand/BodyTalk/Speaking/BodyTalk_19",
    "bodytalk_20":        "animations/Stand/BodyTalk/Speaking/BodyTalk_20",
    "bodytalk_21":        "animations/Stand/BodyTalk/Speaking/BodyTalk_21",
    "bodytalk_22":        "animations/Stand/BodyTalk/Speaking/BodyTalk_22",
    "listening_anim":     "animations/Stand/BodyTalk/Listening/Listening_2",
    "listening_left":     "animations/Stand/BodyTalk/Listening/ListeningLeft_1",
    "listening_right":    "animations/Stand/BodyTalk/Listening/ListeningRight_1",
    "remember":           "animations/Stand/BodyTalk/Thinking/Remember_1",
    "remember_2":         "animations/Stand/BodyTalk/Thinking/Remember_2",
    "remember_3":         "animations/Stand/BodyTalk/Thinking/Remember_3",
    "thinking_loop":      "animations/Stand/BodyTalk/Thinking/ThinkingLoop_1",
    "thinking_loop_2":    "animations/Stand/BodyTalk/Thinking/ThinkingLoop_2",
}

# QTrobot dance names → BEHAVIORS keys
QT_TO_NAO_BEHAVIOR = {
    # Short alias form (legacy)
    "dance":           "funny_dancer",
    "dance_funny":     "funny_dancer",
    "air_guitar":      "air_guitar",
    "bandmaster":      "bandmaster",
    "kung_fu":         "kung_fu",
    "robot_dance":     "robot_dance",
    "zombie":          "zombie",
    "happy_birthday":  "happy_birthday",
    "show_muscles":    "show_muscles",
    "fitness":         "fitness",
    "winner":          "winner",
    "hysterical":      "hysterical",
    "ecstatic":        "ecstatic",
    # Full QTrobot path form (from WOZ state table)
    "qt/happy":                        "happy_anim",
    "qt/laugh":                        "laugh_anim",
    "qt/yes":                          "yes_anim",
    "qt/no":                           "shake_head",
    "qt/so":                           "i_dont_know",
    "qt/so_what":                      "i_dont_know",
    "qt/curious":                      "puzzled",
    "qt/handclap":                     "applause",
    "qt/thanks":                       "bow",
    "qt/bye":                          "wave",
    "qt/strong":                       "show_muscles",
    "qt/challenge":                    "enthusiastic_g",
    "qt/bored":                        "bored_anim",
    "qt/angry":                        "angry_anim",
    "qt/yawn":                         "relaxation",
    "qt/stretch":                      "stretch_wait",
    "qt/peekaboo":                     "hide_eyes",
    "qt/head_scratch":                 "scratch_head",
    "qt/touch-head-back":              "scratch_head",
    "qt/monkey":                       "funny_dancer",
    "qt/hips":                         "funny_dancer",
    "qt/swipe_right":                  "far",
    "qt/show_tablet":                  "give",
    "qt/imitation/head-right-left":    "shake_head",
    "qt/imitation/hands-on-hip":       "show_muscles",
    "qt/imitation/nodding-yes":        "nod",
    # --- QTrobot full-path forms not yet mapped ---
    "qt/hi":                           "wave",
    "qt/surprise":                     "yay",
    "qt/touch-head":                   "pat_pat",
    "qt/emotions/sad":                 "sad",
    "qt/kiss":                         "love_you",
    "qt/face":                         "hide_eyes",
}

# GESTURES aliases for BEHAVIORS names that may not be installed on all NAOs.
# These allow _do_move to fall back to joint-angle sequences when runBehavior fails.
GESTURES["applause"] = GESTURES["clapping"]

# Fallback behavior paths for robots with a reduced animation set.
# Maps missing behavior path → nearest installed alternative.
# Only used when runBehavior() raises an exception.
BEHAVIOR_FALLBACKS = {
    # Gestures missing from some Pepper units
    "animations/Stand/Gestures/Applause_1":          "animations/Stand/Gestures/Enthusiastic_3",
    "animations/Stand/Gestures/Caress_1":            "animations/Stand/Gestures/Please_1",
    "animations/Stand/Gestures/Caress_2":            "animations/Stand/Gestures/Please_2",
    "animations/Stand/Gestures/CatchFly_1":          "animations/Stand/Gestures/Look_1",
    "animations/Stand/Gestures/CatchFly_2":          "animations/Stand/Gestures/Look_2",
    "animations/Stand/Gestures/Choice_2":            "animations/Stand/Gestures/Choice_1",
    "animations/Stand/Gestures/Claw_1":              "animations/Stand/Gestures/IDontKnow_1",
    "animations/Stand/Gestures/Claw_2":              "animations/Stand/Gestures/IDontKnow_2",
    "animations/Stand/Gestures/Coaxing_1":           "animations/Stand/Gestures/CalmDown_1",
    "animations/Stand/Gestures/Coaxing_2":           "animations/Stand/Gestures/CalmDown_2",
    "animations/Stand/Gestures/CountOne_2":          "animations/Stand/Gestures/CountOne_1",
    "animations/Stand/Gestures/CountTwo_2":          "animations/Stand/Gestures/CountTwo_1",
    "animations/Stand/Gestures/CountThree_2":        "animations/Stand/Gestures/CountThree_1",
    "animations/Stand/Gestures/CountFour_2":         "animations/Stand/Gestures/CountFour_1",
    "animations/Stand/Gestures/CountFive_2":         "animations/Stand/Gestures/CountFive_1",
    "animations/Stand/Gestures/CountMore_2":         "animations/Stand/Gestures/CountMore_1",
    "animations/Stand/Gestures/Enthusiastic_1":      "animations/Stand/Gestures/Enthusiastic_3",
    "animations/Stand/Gestures/Enthusiastic_2":      "animations/Stand/Gestures/Enthusiastic_4",
    "animations/Stand/Gestures/Everything_5":        "animations/Stand/Gestures/Everything_4",
    "animations/Stand/Gestures/Explain_9":           "animations/Stand/Gestures/Explain_8",
    "animations/Stand/Gestures/Freeze_1":            "animations/Stand/Gestures/Thinking_1",
    "animations/Stand/Gestures/Hey_5":               "animations/Stand/Gestures/Hey_4",
    "animations/Stand/Gestures/Hungry_1":            "animations/Stand/Gestures/Yum_1",
    "animations/Stand/Gestures/JointHands_1":        "animations/Stand/Gestures/Give_1",
    "animations/Stand/Gestures/JointHands_2":        "animations/Stand/Gestures/Give_2",
    "animations/Stand/Gestures/JointHands_3":        "animations/Stand/Gestures/Give_3",
    "animations/Stand/Gestures/Me_3":               "animations/Stand/Gestures/Me_2",
    "animations/Stand/Gestures/Me_5":               "animations/Stand/Gestures/Me_4",
    "animations/Stand/Gestures/Me_6":               "animations/Stand/Gestures/Me_7",
    "animations/Stand/Gestures/Shoot_1":             "animations/Stand/Gestures/Hey_1",
    # Emotions
    "animations/Stand/Emotions/Neutral/Annoyed_1":   "animations/Stand/Emotions/Neutral/Alienated_1",
    "animations/Stand/Emotions/Neutral/Hello_1":     "animations/Stand/Emotions/Neutral/AskForAttention_1",
    # BodyTalk — cap at highest installed index (16)
    "animations/Stand/BodyTalk/Speaking/BodyTalk_17": "animations/Stand/BodyTalk/Speaking/BodyTalk_16",
    "animations/Stand/BodyTalk/Speaking/BodyTalk_18": "animations/Stand/BodyTalk/Speaking/BodyTalk_16",
    "animations/Stand/BodyTalk/Speaking/BodyTalk_19": "animations/Stand/BodyTalk/Speaking/BodyTalk_16",
    "animations/Stand/BodyTalk/Speaking/BodyTalk_20": "animations/Stand/BodyTalk/Speaking/BodyTalk_16",
    "animations/Stand/BodyTalk/Speaking/BodyTalk_21": "animations/Stand/BodyTalk/Speaking/BodyTalk_16",
    "animations/Stand/BodyTalk/Speaking/BodyTalk_22": "animations/Stand/BodyTalk/Speaking/BodyTalk_16",
    "animations/Stand/BodyTalk/Listening/ListeningLeft_1":  "animations/Stand/BodyTalk/Listening/Listening_2",
    "animations/Stand/BodyTalk/Listening/ListeningRight_1": "animations/Stand/BodyTalk/Listening/Listening_3",
    # Waiting
    "animations/Stand/Waiting/AirJuggle_1":          "animations/Stand/Waiting/AirGuitar_1",
    "animations/Stand/Waiting/FunnySlide_1":         "animations/Stand/Waiting/FunnyDancer_1",
    "animations/Stand/Waiting/Headbang_1":           "animations/Stand/Waiting/Bandmaster_1",
    "animations/Stand/Waiting/Stretch_3":            "animations/Stand/Waiting/Stretch_2",
    "animations/Stand/Waiting/Vacuum_1":             "animations/Stand/Waiting/ScratchBack_1",
    "animations/Stand/Waiting/WalkInTheShit_1":      "animations/Stand/Waiting/FunnyDancer_1",
}
